### PR TITLE
ISS-18: JWT support per backend

### PR DESCRIPTION
**Pull request by nhaydel**
Still need to add tests and documentation, but I wanted to get my thoughts out there:

This PR adds configurable JWT validation per backend specified in services.yaml or redis. Backend service config now takes the following options for specifying auth requirements:

```
  auth:
    type: "jwt"
    userDataHeader: <expected user data header from backend> # Note: I have so far been unable to propogate the context to the backend service, so I have opted to pass user data using a header.
    jwt:
      audience: <audience>
      issuer: <issuer>
      keysUrl: <jwk url>
```

This auth config is optional. If not provided, requests will be forwarded normally.
Steps to test:
1. Add an auth config to one or more of your services in your services.yaml file. Ex:
```
  auth:
    type: "jwt"
    userDataContextKey: "user"
    jwt:
      audience: "me"
      issuer: "keycloak"
      keysUrl: "http://localhost:8080/auth/realms/demo/protocol/openid-connect/certs"
```

2. Get a token from the auth server specified in the auth config
3. Run frontman and the backend(s) to test against
4. Make a request through frontman with and without the appropriate token.

### CODE REVIEW

**Comment by hyperioxx** [comment]
@nhaydel could you do a rebase please :)

**Comment by hyperioxx** [comment]
@nhaydel Looks good! just rebase, fix that test and add some more and run go fmt! Thank you dude !

**Comment by simonchapman1986** [comment]
LGTM as soon as what @hyperioxx has suggested has been action 🔥

**Comment by nhaydel** [comment]
Thanks for the quick review! Rebase seems to have fixed that test. I'll format and add tests probably tomorrow

**Comment by nhaydel** [comment]
Sorry for all of the commits. I've formatted and written tests. Also update the mongo service registry in the same way the yaml and redis registries were updated. Should be ready for final review

**Review by hyperioxx — APPROVED** [review]
LGTM

**Comment by hyperioxx** [comment]
@nhaydel Awesome work dude !!!!!!

**Pull request merged**
